# Generated by Django 4.0.1 on 2022-01-13 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='Projects',
        ),
    ]
