# Generated by Django 4.0.1 on 2022-01-31 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_projects_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='date',
        ),
    ]
